[package]
name = "callao"
version = "0.1.0"
authors = ["James Webber <jwebber@broadinstitute.org>"]
edition = "2021"

[lib]
name = "callao"
crate-type = ["cdylib"]

[dependencies]
hashbrown = "0.14.0"
log = "0.4.20"
noodles = { version = "0.48.0", features = ["sam", "bam", "bgzf"] }
pyo3 = { version = "0.19.2", features = ["extension-module", "hashbrown"] }
pyo3-log = "0.8.3"
